### ISSUE TITLE
SSP-To is being set to nhsMhsId not nhsSpineAsid

### ISSUE THREAD

**Issue by no-man-is-an-island** [NHSDigital/integration-adaptor-gpc-consumer#69]
Affects Version: 1.3.0-prototype

In the prototype release where the SSP-To is being set dynamically when not present, the nhsMhsId field from SDS is being used (e.g. `1d0ba8b83eb59eb7f235`). This is *not* the ASID and will not be accepted by SSP. The correct field to use is nhsSpineASID.

Example SDS FHIR response (identifier section):

```
"identifier": [
                    {
                        "system": "https://fhir.nhs.uk/Id/nhsSpineASID",
                        "value": "200000001073"
                    },
                    {
                        "system": "https://fhir.nhs.uk/Id/nhsMhsPartyKey",
                        "value": "N82103-821992"
                    }
                ],
```

**Comment by adrianclay** [comment]
Closed, as no steps to reproduce and testing has shown that the correct ASID is being generated for `Ssp-From` and `Ssp-To`.
